/****** Object:  Table [dbo].[Sales]    Script Date: 12/22/2019 9:04:44 PM ******/
DROP TABLE [dbo].[Sales]
GO

/****** Object:  Table [dbo].[Sales]    Script Date: 12/22/2019 9:04:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_ID] [varchar](20) NOT NULL,
	[ORDER_DATE] [date] NOT NULL,
	[SHIP_DATE] [date] NOT NULL,
	[SHIP_MODE] [varchar](20) NULL,
	[QUANTITY] [int] NOT NULL,
	[DISCOUNT] [decimal](3, 2) NULL,
	[PROFIT] [decimal](6, 2) NOT NULL,
	[PRODUCT_ID] [varchar](20) NOT NULL,
	[CUSTOMER_NAME] [varchar](255) NOT NULL,
	[CATEGORY] [varchar](255) NOT NULL,
	[CUSTOMER_ID] [varchar](20) NOT NULL,
	[PRODUCT_NAME] [varchar](255) NULL,
 CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


